import {
  Wrench, Zap, Hammer, Sofa, Building2, PaintBucket, Sparkles,
  Bug, Tv, Wind, Wifi, Shield, Leaf, Truck, Car as CarIcon,
  Shirt, Droplet, Palette, Hospital, Settings,
  Sun, Flame, Layers, PawPrint, Baby, UtensilsCrossed, Scissors,
  Dumbbell, Camera, Laptop, Package, Music, BookOpen, Bike, Waves,
} from "lucide-react";

export const SERVICE_CATEGORIES = [
  { id: "plumbing",     name: "Plumbing",            icon: Wrench,          color: "from-blue-500 to-blue-600",     range: "200-800"   },
  { id: "electrical",   name: "Electrical",           icon: Zap,             color: "from-yellow-500 to-yellow-600", range: "300-1000"  },
  { id: "carpentry",    name: "Carpentry",            icon: Hammer,          color: "from-amber-600 to-amber-700",   range: "400-1200"  },
  { id: "furniture",    name: "Furniture",            icon: Sofa,            color: "from-purple-500 to-purple-600", range: "500-2000"  },
  { id: "construction", name: "Construction",         icon: Building2,       color: "from-gray-600 to-gray-700",     range: "2000+"     },
  { id: "painting",     name: "Painting",             icon: PaintBucket,     color: "from-pink-500 to-pink-600",     range: "300-1500"  },
  { id: "cleaning",     name: "Cleaning",             icon: Sparkles,        color: "from-cyan-500 to-cyan-600",     range: "200-600"   },
  { id: "pest",         name: "Pest Control",         icon: Bug,             color: "from-red-500 to-red-600",       range: "400-1000"  },
  { id: "appliance",    name: "Appliance Repair",     icon: Tv,              color: "from-indigo-500 to-indigo-600", range: "300-1200"  },
  { id: "ac",           name: "AC Service",           icon: Wind,            color: "from-blue-400 to-blue-500",     range: "500-1500"  },
  { id: "internet",     name: "Internet/WiFi",        icon: Wifi,            color: "from-green-500 to-green-600",   range: "300-800"   },
  { id: "security",     name: "Security Systems",     icon: Shield,          color: "from-slate-600 to-slate-700",   range: "1000-3000" },
  { id: "gardening",    name: "Gardening",            icon: Leaf,            color: "from-green-600 to-green-700",   range: "250-700"   },
  { id: "movers",       name: "Movers & Packers",     icon: Truck,           color: "from-orange-500 to-orange-600", range: "1500-5000" },
  { id: "vehicle",      name: "Vehicle Repair",       icon: CarIcon,         color: "from-red-600 to-red-700",       range: "500-2000"  },
  { id: "laundry",      name: "Laundry",              icon: Shirt,           color: "from-blue-300 to-blue-400",     range: "150-500"   },
  { id: "water",        name: "Water Supply",         icon: Droplet,         color: "from-cyan-600 to-cyan-700",     range: "200-600"   },
  { id: "interior",     name: "Interior Design",      icon: Palette,         color: "from-purple-600 to-purple-700", range: "2000+"     },
  { id: "emergency",    name: "Emergency (Hospital)", icon: Hospital,        color: "from-red-700 to-red-800",       range: "1000+"     },
  { id: "maintenance",  name: "General Maintenance",  icon: Settings,        color: "from-gray-500 to-gray-600",     range: "250-900"   },
  { id: "solar",        name: "Solar & Energy",       icon: Sun,             color: "from-yellow-400 to-orange-500", range: "500-3000"  },
  { id: "gas",          name: "Gas & Pipeline",       icon: Flame,           color: "from-orange-600 to-red-600",    range: "300-1500"  },
  { id: "flooring",     name: "Flooring & Tiling",    icon: Layers,          color: "from-stone-500 to-stone-600",   range: "1000-5000" },
  { id: "pet",          name: "Pet Services",         icon: PawPrint,        color: "from-amber-500 to-yellow-600",  range: "200-800"   },
  { id: "childcare",    name: "Baby & Elder Care",    icon: Baby,            color: "from-pink-400 to-rose-500",     range: "300-1200"  },
  { id: "food",         name: "Food & Catering",      icon: UtensilsCrossed, color: "from-orange-400 to-amber-500",  range: "200-2000"  },
  { id: "beauty",       name: "Beauty & Wellness",    icon: Scissors,        color: "from-fuchsia-500 to-pink-600",  range: "200-1500"  },
  { id: "fitness",      name: "Fitness & Yoga",       icon: Dumbbell,        color: "from-lime-500 to-green-600",    range: "300-1000"  },
  { id: "photography",  name: "Photography",          icon: Camera,          color: "from-violet-500 to-purple-600", range: "500-5000"  },
  { id: "it",           name: "IT & Tech Support",    icon: Laptop,          color: "from-sky-500 to-blue-600",      range: "300-2000"  },
  { id: "courier",      name: "Courier & Delivery",   icon: Package,         color: "from-teal-500 to-cyan-600",     range: "50-500"    },
  { id: "music",        name: "Music & Classes",      icon: Music,           color: "from-indigo-400 to-violet-500", range: "500-2000"  },
  { id: "tutoring",     name: "Tutoring & Education", icon: BookOpen,        color: "from-blue-600 to-indigo-700",   range: "300-1500"  },
  { id: "carwash",      name: "Car Wash & Detailing", icon: Bike,            color: "from-sky-400 to-blue-500",      range: "200-1500"  },
  { id: "pool",         name: "Pool & Water Tank",    icon: Waves,           color: "from-cyan-400 to-teal-500",     range: "500-3000"  },
];
