// Partner companies data
export const PARTNERS = [
  { id: 1, name: "QuickFix Plumbing", category: "plumbing", desc: "24/7 emergency plumbing services", price: "199", discount: "10% off", rating: 4.8, contact: { personName: "Ramesh Kumar", phone: "9876543210" } },
  { id: 2, name: "AquaPro Solutions", category: "plumbing", desc: "Expert leak detection & repair", price: "249", discount: "15% off", rating: 4.7, contact: { personName: "Suresh Patel", phone: "9823456701" } },
  { id: 3, name: "PowerLine Electricals", category: "electrical", desc: "Licensed electricians for all needs", price: "299", discount: "10% off", rating: 4.9, contact: { personName: "Anil Sharma", phone: "9812345678" } },
  { id: 4, name: "BrightSpark Services", category: "electrical", desc: "Wiring, fittings & safety checks", price: "349", discount: "12% off", rating: 4.6, contact: { personName: "Vijay Singh", phone: "9834567890" } },
  { id: 5, name: "WoodCraft Masters", category: "carpentry", desc: "Custom furniture & repairs", price: "399", discount: "10% off", rating: 4.8, contact: { personName: "Mohan Das", phone: "9845678901" } },
  { id: 6, name: "Timber Touch", category: "carpentry", desc: "Door, window & cabinet work", price: "449", discount: "8% off", rating: 4.5, contact: { personName: "Rajan Verma", phone: "9856789012" } },
  { id: 7, name: "ComfortZone Furniture", category: "furniture", desc: "Sofa, bed & wardrobe assembly", price: "499", discount: "15% off", rating: 4.7, contact: { personName: "Deepak Gupta", phone: "9867890123" } },
  { id: 8, name: "HomeStyle Furnishings", category: "furniture", desc: "Modular furniture installation", price: "599", discount: "10% off", rating: 4.6, contact: { personName: "Sanjay Mehta", phone: "9878901234" } },
  { id: 9, name: "BuildRight Contractors", category: "construction", desc: "Renovation & construction experts", price: "2000", discount: "5% off", rating: 4.9, contact: { personName: "Prakash Rao", phone: "9889012345" } },
  { id: 10, name: "SolidBase Builders", category: "construction", desc: "Structural work & extensions", price: "2500", discount: "7% off", rating: 4.8, contact: { personName: "Harish Nair", phone: "9890123456" } },
  { id: 11, name: "ColorPalette Painters", category: "painting", desc: "Interior & exterior painting", price: "299", discount: "12% off", rating: 4.7, contact: { personName: "Rakesh Joshi", phone: "9901234567" } },
  { id: 12, name: "FreshCoat Services", category: "painting", desc: "Texture & waterproofing", price: "349", discount: "10% off", rating: 4.6, contact: { personName: "Dinesh Tiwari", phone: "9912345678" } },
  { id: 13, name: "SparkleClean Pro", category: "cleaning", desc: "Deep cleaning & sanitization", price: "199", discount: "15% off", rating: 4.8, contact: { personName: "Sunil Yadav", phone: "9923456789" } },
  { id: 14, name: "ShineOn Cleaners", category: "cleaning", desc: "Home & office cleaning", price: "249", discount: "10% off", rating: 4.5, contact: { personName: "Manoj Pandey", phone: "9934567890" } },
  { id: 15, name: "BugBusters", category: "pest", desc: "Termite, cockroach & rodent control", price: "399", discount: "10% off", rating: 4.9, contact: { personName: "Ashok Mishra", phone: "9945678901" } },
  { id: 16, name: "PestFree Solutions", category: "pest", desc: "Eco-friendly pest management", price: "449", discount: "12% off", rating: 4.7, contact: { personName: "Santosh Dubey", phone: "9956789012" } },
  { id: 17, name: "FixIt Appliances", category: "appliance", desc: "Fridge, washing machine repair", price: "299", discount: "10% off", rating: 4.6, contact: { personName: "Rajesh Pillai", phone: "9967890123" } },
  { id: 18, name: "HomeAppliance Care", category: "appliance", desc: "Microwave, TV & electronics", price: "349", discount: "8% off", rating: 4.5, contact: { personName: "Naresh Iyer", phone: "9978901234" } },
  { id: 19, name: "CoolBreeze AC Services", category: "ac", desc: "AC installation, repair & servicing", price: "499", discount: "15% off", rating: 4.8, contact: { personName: "Girish Menon", phone: "9989012345" } },
  { id: 20, name: "ChillZone Cooling", category: "ac", desc: "Gas refill & maintenance", price: "599", discount: "10% off", rating: 4.7, contact: { personName: "Umesh Reddy", phone: "9990123456" } },
  { id: 21, name: "NetSpeed Broadband", category: "internet", desc: "High-speed internet installation", price: "299", discount: "20% off", rating: 4.9, contact: { personName: "Kiran Bhat", phone: "9901234568" } },
  { id: 22, name: "ConnectPlus WiFi", category: "internet", desc: "Router setup & troubleshooting", price: "349", discount: "15% off", rating: 4.6, contact: { personName: "Tarun Saxena", phone: "9812345679" } },
  { id: 23, name: "SecureHome Systems", category: "security", desc: "CCTV & alarm installation", price: "999", discount: "10% off", rating: 4.8, contact: { personName: "Pawan Chauhan", phone: "9823456702" } },
  { id: 24, name: "SafeGuard Security", category: "security", desc: "Smart locks & monitoring", price: "1199", discount: "12% off", rating: 4.7, contact: { personName: "Rohit Srivastava", phone: "9834567891" } },
  { id: 25, name: "GreenThumb Gardeners", category: "gardening", desc: "Lawn care & plant maintenance", price: "249", discount: "10% off", rating: 4.6, contact: { personName: "Amit Tripathi", phone: "9845678902" } },
  { id: 26, name: "BloomScape Services", category: "gardening", desc: "Landscaping & terrace gardens", price: "299", discount: "15% off", rating: 4.5, contact: { personName: "Nitin Shukla", phone: "9856789013" } },
  { id: 27, name: "SwiftMove Packers", category: "movers", desc: "Local & intercity shifting", price: "1499", discount: "10% off", rating: 4.9, contact: { personName: "Vivek Agarwal", phone: "9867890124" } },
  { id: 28, name: "EasyShift Movers", category: "movers", desc: "Packing, loading & transport", price: "1799", discount: "8% off", rating: 4.7, contact: { personName: "Gaurav Bajaj", phone: "9878901235" } },
  { id: 29, name: "AutoCare Garage", category: "vehicle", desc: "Car & bike servicing", price: "499", discount: "12% off", rating: 4.8, contact: { personName: "Hemant Kapoor", phone: "9889012346" } },
  { id: 30, name: "WheelFix Mechanics", category: "vehicle", desc: "Denting, painting & repairs", price: "599", discount: "10% off", rating: 4.6, contact: { personName: "Ajay Malhotra", phone: "9890123457" } },
  { id: 31, name: "FreshWash Laundry", category: "laundry", desc: "Dry cleaning & ironing", price: "149", discount: "15% off", rating: 4.7, contact: { personName: "Saurabh Bansal", phone: "9901234569" } },
  { id: 32, name: "CleanPress Services", category: "laundry", desc: "Pickup & delivery laundry", price: "199", discount: "10% off", rating: 4.5, contact: { personName: "Pradeep Arora", phone: "9912345679" } },
  { id: 33, name: "AquaFlow Water Supply", category: "water", desc: "Tanker & pipeline services", price: "199", discount: "10% off", rating: 4.6, contact: { personName: "Manish Goel", phone: "9923456780" } },
  { id: 34, name: "PureWater Solutions", category: "water", desc: "Water purifier installation", price: "249", discount: "12% off", rating: 4.7, contact: { personName: "Vinod Mittal", phone: "9934567891" } },
  { id: 35, name: "DesignHub Interiors", category: "interior", desc: "Complete home makeover", price: "1999", discount: "10% off", rating: 4.9, contact: { personName: "Arun Khanna", phone: "9945678902" } },
  { id: 36, name: "ModernLiving Designs", category: "interior", desc: "3D design & execution", price: "2499", discount: "8% off", rating: 4.8, contact: { personName: "Suresh Bose", phone: "9956789013" } },
  { id: 37, name: "LifeCare Hospital", category: "emergency", desc: "24/7 emergency ambulance", price: "999", discount: "Society rate", rating: 4.9, contact: { personName: "Ravi Chandra", phone: "9967890124" } },
  { id: 38, name: "MediQuick Services", category: "emergency", desc: "Home healthcare & nursing", price: "1199", discount: "15% off", rating: 4.7, contact: { personName: "Anand Pillai", phone: "9978901235" } },
  { id: 39, name: "HandyFix Maintenance", category: "maintenance", desc: "All-in-one home repairs", price: "249", discount: "10% off", rating: 4.8, contact: { personName: "Bharat Sinha", phone: "9989012346" } },
  { id: 40, name: "QuickRepair Services", category: "maintenance", desc: "Minor fixes & installations", price: "299", discount: "12% off", rating: 4.6, contact: { personName: "Dinesh Rawat", phone: "9990123457" } },
  { id: 41, name: "PipeMaster Pro", category: "plumbing", desc: "Bathroom fittings & pipeline work", price: "229", discount: "8% off", rating: 4.7, contact: { personName: "Suresh Nambiar", phone: "9876501234" } },
  { id: 42, name: "DrainClear Experts", category: "plumbing", desc: "Drain unblocking & sewer cleaning", price: "279", discount: "10% off", rating: 4.6, contact: { personName: "Rajan Pillai", phone: "9823401235" } },
  { id: 43, name: "TapFix Services", category: "plumbing", desc: "Tap, mixer & shower repairs", price: "189", discount: "12% off", rating: 4.5, contact: { personName: "Mohan Shetty", phone: "9812301236" } },
  { id: 44, name: "VoltCare Electricals", category: "electrical", desc: "MCB, fuse & panel repairs", price: "319", discount: "10% off", rating: 4.8, contact: { personName: "Anil Kulkarni", phone: "9834501237" } },
  { id: 45, name: "WireWise Solutions", category: "electrical", desc: "Concealed wiring & conduit work", price: "369", discount: "8% off", rating: 4.7, contact: { personName: "Vijay Desai", phone: "9845601238" } },
  { id: 46, name: "LightUp Electricians", category: "electrical", desc: "LED fitting & smart switches", price: "289", discount: "15% off", rating: 4.6, contact: { personName: "Deepak Joshi", phone: "9856701239" } },
  { id: 47, name: "CraftWood Interiors", category: "carpentry", desc: "Modular kitchen & wardrobe work", price: "479", discount: "10% off", rating: 4.8, contact: { personName: "Sanjay Patil", phone: "9867801240" } },
  { id: 48, name: "JoineryPlus", category: "carpentry", desc: "Staircase, railing & shelf work", price: "429", discount: "8% off", rating: 4.6, contact: { personName: "Prakash Hegde", phone: "9878901241" } },
  { id: 49, name: "FlatPack Experts", category: "furniture", desc: "IKEA & flat-pack assembly", price: "449", discount: "12% off", rating: 4.7, contact: { personName: "Harish Kamath", phone: "9889001242" } },
  { id: 50, name: "SofaRescue Services", category: "furniture", desc: "Sofa repair, foam & upholstery", price: "549", discount: "10% off", rating: 4.5, contact: { personName: "Rakesh Naik", phone: "9890101243" } },
  { id: 51, name: "WallArt Painters", category: "painting", desc: "Stencil, texture & wall art", price: "379", discount: "10% off", rating: 4.8, contact: { personName: "Dinesh Sawant", phone: "9901201244" } },
  { id: 52, name: "ProCoat Painting", category: "painting", desc: "Waterproof & anti-fungal coating", price: "329", discount: "12% off", rating: 4.7, contact: { personName: "Sunil Pawar", phone: "9912301245" } },
  { id: 53, name: "FreshHome Cleaners", category: "cleaning", desc: "Move-in/move-out deep cleaning", price: "279", discount: "12% off", rating: 4.7, contact: { personName: "Manoj Salvi", phone: "9923401246" } },
  { id: 54, name: "SteamClean Pro", category: "cleaning", desc: "Sofa, carpet & mattress cleaning", price: "349", discount: "10% off", rating: 4.8, contact: { personName: "Ashok Gawde", phone: "9934501247" } },
  { id: 55, name: "GlassShine Services", category: "cleaning", desc: "Window & glass facade cleaning", price: "219", discount: "8% off", rating: 4.5, contact: { personName: "Santosh More", phone: "9945601248" } },
  { id: 56, name: "ZeroTermite Co.", category: "pest", desc: "Pre & post-construction termite treatment", price: "499", discount: "10% off", rating: 4.8, contact: { personName: "Rajesh Bhosale", phone: "9956701249" } },
  { id: 57, name: "BedBugBusters", category: "pest", desc: "Bed bug heat treatment", price: "549", discount: "8% off", rating: 4.7, contact: { personName: "Naresh Jadhav", phone: "9967801250" } },
  { id: 58, name: "CoolFix Appliances", category: "appliance", desc: "Refrigerator & freezer repair", price: "329", discount: "10% off", rating: 4.7, contact: { personName: "Girish Mane", phone: "9978901251" } },
  { id: 59, name: "WashCare Services", category: "appliance", desc: "Washing machine & dryer repair", price: "299", discount: "12% off", rating: 4.6, contact: { personName: "Umesh Shinde", phone: "9989001252" } },
  { id: 60, name: "SmartTV Repairs", category: "appliance", desc: "LED, LCD & smart TV servicing", price: "379", discount: "8% off", rating: 4.5, contact: { personName: "Kiran Deshpande", phone: "9990101253" } },
  { id: 61, name: "ArcticAir Services", category: "ac", desc: "Split & window AC installation", price: "549", discount: "12% off", rating: 4.8, contact: { personName: "Tarun Wagh", phone: "9901201254" } },
  { id: 62, name: "FrostFree Cooling", category: "ac", desc: "Annual AMC & gas top-up", price: "649", discount: "10% off", rating: 4.7, contact: { personName: "Pawan Kale", phone: "9812301255" } },
  { id: 63, name: "FiberLink Broadband", category: "internet", desc: "Fiber optic connection setup", price: "399", discount: "18% off", rating: 4.9, contact: { personName: "Rohit Thakur", phone: "9823401256" } },
  { id: 64, name: "MeshNet Solutions", category: "internet", desc: "Whole-home mesh WiFi setup", price: "449", discount: "12% off", rating: 4.7, contact: { personName: "Amit Chavan", phone: "9834501257" } },
  { id: 65, name: "VaultGuard Systems", category: "security", desc: "Video doorbell & intercom setup", price: "1099", discount: "10% off", rating: 4.8, contact: { personName: "Nitin Kamble", phone: "9845601258" } },
  { id: 66, name: "SmartLock Pro", category: "security", desc: "Biometric & digital lock installation", price: "1299", discount: "8% off", rating: 4.7, contact: { personName: "Vivek Lokhande", phone: "9856701259" } },
  { id: 67, name: "TerraceFarm Co.", category: "gardening", desc: "Terrace vegetable garden setup", price: "349", discount: "12% off", rating: 4.7, contact: { personName: "Gaurav Thorat", phone: "9867801260" } },
  { id: 68, name: "AquaGarden Services", category: "gardening", desc: "Drip irrigation & auto-watering", price: "399", discount: "10% off", rating: 4.6, contact: { personName: "Hemant Gaikwad", phone: "9878901261" } },
  { id: 69, name: "TreeCare Experts", category: "gardening", desc: "Tree trimming & stump removal", price: "449", discount: "8% off", rating: 4.5, contact: { personName: "Ajay Waghmare", phone: "9889001262" } },
  { id: 70, name: "SafeShift Packers", category: "movers", desc: "Fragile & antique item shifting", price: "1999", discount: "10% off", rating: 4.8, contact: { personName: "Saurabh Dhole", phone: "9890101263" } },
  { id: 71, name: "MiniMove Services", category: "movers", desc: "Single-room & small moves", price: "999", discount: "12% off", rating: 4.7, contact: { personName: "Pradeep Surve", phone: "9901201264" } },
  { id: 72, name: "BikeDoc Garage", category: "vehicle", desc: "Two-wheeler service & repair", price: "399", discount: "15% off", rating: 4.7, contact: { personName: "Manish Rane", phone: "9912301265" } },
  { id: 73, name: "DentFix Auto", category: "vehicle", desc: "Car denting, painting & polish", price: "699", discount: "10% off", rating: 4.6, contact: { personName: "Vinod Gharat", phone: "9923401266" } },
  { id: 74, name: "TyrePoint Services", category: "vehicle", desc: "Tyre change, balancing & alignment", price: "349", discount: "8% off", rating: 4.5, contact: { personName: "Arun Bendre", phone: "9934501267" } },
  { id: 75, name: "SteamPress Laundry", category: "laundry", desc: "Bulk laundry & curtain cleaning", price: "229", discount: "12% off", rating: 4.7, contact: { personName: "Suresh Dalvi", phone: "9945601268" } },
  { id: 76, name: "QuickDry Services", category: "laundry", desc: "Same-day express laundry", price: "269", discount: "10% off", rating: 4.6, contact: { personName: "Ravi Powar", phone: "9956701269" } },
  { id: 77, name: "TankClean Pro", category: "water", desc: "Overhead & underground tank cleaning", price: "299", discount: "10% off", rating: 4.7, contact: { personName: "Anand Tawde", phone: "9967801270" } },
  { id: 78, name: "RO Masters", category: "water", desc: "RO purifier service & filter change", price: "279", discount: "12% off", rating: 4.8, contact: { personName: "Bharat Koli", phone: "9978901271" } },
  { id: 79, name: "SpaceStudio Designs", category: "interior", desc: "Compact flat space optimization", price: "2299", discount: "10% off", rating: 4.8, contact: { personName: "Dinesh Bhoir", phone: "9989001272" } },
  { id: 80, name: "LuxeHome Interiors", category: "interior", desc: "Premium turnkey interior solutions", price: "3499", discount: "7% off", rating: 4.9, contact: { personName: "Suresh Agre", phone: "9990101273" } },
  { id: 81, name: "RapidCare Ambulance", category: "emergency", desc: "BLS & ALS ambulance on call", price: "799", discount: "Society rate", rating: 4.8, contact: { personName: "Ravi Tandel", phone: "9901201274" } },
  { id: 82, name: "HomeNurse Services", category: "emergency", desc: "Post-surgery & elderly home care", price: "1099", discount: "10% off", rating: 4.7, contact: { personName: "Anand Pagare", phone: "9812301275" } },
  { id: 83, name: "DocOnCall", category: "emergency", desc: "Doctor home visit within 60 min", price: "699", discount: "Society rate", rating: 4.9, contact: { personName: "Bharat Kokate", phone: "9823401276" } },
  { id: 84, name: "FixAll Handymen", category: "maintenance", desc: "Drilling, mounting & odd jobs", price: "199", discount: "15% off", rating: 4.7, contact: { personName: "Dinesh Mhatre", phone: "9834501277" } },
  { id: 85, name: "SocietyMaintain Co.", category: "maintenance", desc: "Scheduled society upkeep contracts", price: "349", discount: "10% off", rating: 4.8, contact: { personName: "Suresh Patkar", phone: "9845601278" } },
  { id: 86, name: "RapidFix Services", category: "maintenance", desc: "Same-day minor repair visits", price: "229", discount: "12% off", rating: 4.6, contact: { personName: "Ravi Pednekar", phone: "9856701279" } },
  { id: 87, name: "SunPower Solar", category: "solar", desc: "Solar panel installation & cleaning", price: "499", discount: "10% off", rating: 4.9, contact: { personName: "Suresh Surve", phone: "9867801280" } },
  { id: 88, name: "GreenWatt Energy", category: "solar", desc: "Inverter & UPS installation/repair", price: "399", discount: "8% off", rating: 4.7, contact: { personName: "Anand Bhoir", phone: "9878901281" } },
  { id: 89, name: "EcoVolt Solutions", category: "solar", desc: "Generator servicing & AMC", price: "549", discount: "12% off", rating: 4.6, contact: { personName: "Bharat Agre", phone: "9889001282" } },
  { id: 90, name: "BrightSun Systems", category: "solar", desc: "Rooftop solar & net metering setup", price: "599", discount: "10% off", rating: 4.8, contact: { personName: "Dinesh Tandel", phone: "9890101283" } },
  { id: 91, name: "SafeGas Services", category: "gas", desc: "Gas leak detection & repair", price: "299", discount: "10% off", rating: 4.9, contact: { personName: "Ravi Pagare", phone: "9901201284" } },
  { id: 92, name: "PipelineXpert", category: "gas", desc: "PNG pipeline installation & fitting", price: "349", discount: "8% off", rating: 4.7, contact: { personName: "Anand Kokate", phone: "9912301285" } },
  { id: 93, name: "CylinderDoor", category: "gas", desc: "LPG cylinder home delivery", price: "99", discount: "Society rate", rating: 4.6, contact: { personName: "Bharat Mhatre", phone: "9923401286" } },
  { id: 94, name: "GasGuard Pro", category: "gas", desc: "Gas regulator & hose replacement", price: "249", discount: "12% off", rating: 4.8, contact: { personName: "Suresh Patkar", phone: "9934501287" } },
  { id: 95, name: "TileKing Services", category: "flooring", desc: "Floor & wall tile installation", price: "799", discount: "10% off", rating: 4.8, contact: { personName: "Kiran Sawant", phone: "9945601288" } },
  { id: 96, name: "MarbleShine Pro", category: "flooring", desc: "Marble & granite polishing", price: "699", discount: "12% off", rating: 4.7, contact: { personName: "Tarun Pawar", phone: "9956701289" } },
  { id: 97, name: "EpoxyFloor Experts", category: "flooring", desc: "Epoxy & anti-skid floor coating", price: "999", discount: "8% off", rating: 4.6, contact: { personName: "Pawan Salvi", phone: "9967801290" } },
  { id: 98, name: "WoodFloor Studio", category: "flooring", desc: "Wooden & laminate flooring", price: "1199", discount: "10% off", rating: 4.9, contact: { personName: "Rohit Gawde", phone: "9978901291" } },
  { id: 99, name: "GroutFix Services", category: "flooring", desc: "Tile grout repair & re-grouting", price: "499", discount: "15% off", rating: 4.5, contact: { personName: "Amit More", phone: "9989001292" } },
  { id: 100, name: "PawCare Grooming", category: "pet", desc: "Dog & cat grooming at home", price: "299", discount: "10% off", rating: 4.8, contact: { personName: "Nitin Bhosale", phone: "9990101293" } },
  { id: 101, name: "WoofWalk Services", category: "pet", desc: "Daily dog walking & exercise", price: "199", discount: "15% off", rating: 4.7, contact: { personName: "Vivek Jadhav", phone: "9901201294" } },
  { id: 102, name: "VetOnCall", category: "pet", desc: "Vet home visit & vaccination", price: "499", discount: "Society rate", rating: 4.9, contact: { personName: "Gaurav Mane", phone: "9812301295" } },
  { id: 103, name: "PetSit Pro", category: "pet", desc: "Pet boarding & day care", price: "399", discount: "10% off", rating: 4.6, contact: { personName: "Hemant Shinde", phone: "9823401296" } },
  { id: 104, name: "FurFresh Bath", category: "pet", desc: "Pet bathing, nail trim & ear clean", price: "249", discount: "12% off", rating: 4.7, contact: { personName: "Ajay Deshpande", phone: "9834501297" } },
  { id: 105, name: "TinySteps Nanny", category: "childcare", desc: "Trained babysitters & nannies", price: "499", discount: "10% off", rating: 4.8, contact: { personName: "Saurabh Wagh", phone: "9845601298" } },
  { id: 106, name: "ElderEase Care", category: "childcare", desc: "Elderly companion & daily care", price: "599", discount: "8% off", rating: 4.7, contact: { personName: "Pradeep Kale", phone: "9856701299" } },
  { id: 107, name: "PhysioHome Services", category: "childcare", desc: "Physiotherapy at home", price: "699", discount: "12% off", rating: 4.9, contact: { personName: "Manish Thakur", phone: "9867801300" } },
  { id: 108, name: "BabyBliss Care", category: "childcare", desc: "Newborn care & mother support", price: "799", discount: "10% off", rating: 4.8, contact: { personName: "Vinod Chavan", phone: "9878901301" } },
  { id: 109, name: "SeniorCare Plus", category: "childcare", desc: "Medical escort & hospital assistance", price: "549", discount: "Society rate", rating: 4.6, contact: { personName: "Arun Kamble", phone: "9889001302" } },
  { id: 110, name: "TiffinBox Services", category: "food", desc: "Daily home-cooked tiffin delivery", price: "149", discount: "10% off", rating: 4.8, contact: { personName: "Suresh Lokhande", phone: "9890101303" } },
  { id: 111, name: "FeastCraft Catering", category: "food", desc: "Event & party catering", price: "999", discount: "8% off", rating: 4.7, contact: { personName: "Ravi Thorat", phone: "9901201304" } },
  { id: 112, name: "CakeBake Studio", category: "food", desc: "Custom cakes & desserts on order", price: "399", discount: "15% off", rating: 4.9, contact: { personName: "Anand Gaikwad", phone: "9912301305" } },
  { id: 113, name: "ChefAtHome", category: "food", desc: "Personal chef for parties & events", price: "1499", discount: "10% off", rating: 4.8, contact: { personName: "Bharat Waghmare", phone: "9923401306" } },
  { id: 114, name: "HealthyBite Meals", category: "food", desc: "Diet & nutrition meal plans", price: "199", discount: "12% off", rating: 4.6, contact: { personName: "Dinesh Dhole", phone: "9934501307" } },
  { id: 115, name: "BreakfastBox Co.", category: "food", desc: "Morning breakfast delivery service", price: "99", discount: "10% off", rating: 4.5, contact: { personName: "Suresh Surve", phone: "9945601308" } },
  { id: 116, name: "GlowUp Salon", category: "beauty", desc: "Haircut, facial & beauty at home", price: "299", discount: "15% off", rating: 4.8, contact: { personName: "Priya Sharma", phone: "9956701309" } },
  { id: 117, name: "ZenTouch Massage", category: "beauty", desc: "Relaxation & therapeutic massage", price: "499", discount: "10% off", rating: 4.7, contact: { personName: "Neha Kulkarni", phone: "9967801310" } },
  { id: 118, name: "NailArt Studio", category: "beauty", desc: "Manicure, pedicure & nail art", price: "249", discount: "12% off", rating: 4.6, contact: { personName: "Pooja Desai", phone: "9978901311" } },
  { id: 119, name: "BridalGlow Services", category: "beauty", desc: "Bridal makeup & pre-wedding packages", price: "1999", discount: "8% off", rating: 4.9, contact: { personName: "Anjali Patil", phone: "9989001312" } },
  { id: 120, name: "MensCut Pro", category: "beauty", desc: "Men's haircut & grooming at home", price: "199", discount: "10% off", rating: 4.5, contact: { personName: "Rahul Hegde", phone: "9990101313" } },
  { id: 121, name: "YogaZone Classes", category: "fitness", desc: "Morning yoga sessions at home/terrace", price: "399", discount: "10% off", rating: 4.9, contact: { personName: "Sunita Kamath", phone: "9901201314" } },
  { id: 122, name: "FitLife Trainer", category: "fitness", desc: "Personal fitness trainer at home", price: "599", discount: "8% off", rating: 4.8, contact: { personName: "Vikram Naik", phone: "9812301315" } },
  { id: 123, name: "ZumbaBeats Classes", category: "fitness", desc: "Zumba & aerobics group sessions", price: "299", discount: "15% off", rating: 4.7, contact: { personName: "Kavita Sawant", phone: "9823401316" } },
  { id: 124, name: "MeditateNow", category: "fitness", desc: "Guided meditation & mindfulness", price: "249", discount: "12% off", rating: 4.6, contact: { personName: "Meena Pawar", phone: "9834501317" } },
  { id: 125, name: "KidsGym Fun", category: "fitness", desc: "Children's fitness & activity classes", price: "349", discount: "10% off", rating: 4.7, contact: { personName: "Arjun Salvi", phone: "9845601318" } },
  { id: 126, name: "ClickPerfect Studio", category: "photography", desc: "Event & birthday photography", price: "1499", discount: "10% off", rating: 4.9, contact: { personName: "Rohan Gawde", phone: "9856701319" } },
  { id: 127, name: "PassportSnap", category: "photography", desc: "Passport & ID photo at home", price: "149", discount: "Society rate", rating: 4.6, contact: { personName: "Sneha More", phone: "9867801320" } },
  { id: 128, name: "ReelMoments Video", category: "photography", desc: "Event videography & reels", price: "1999", discount: "8% off", rating: 4.8, contact: { personName: "Akash Bhosale", phone: "9878901321" } },
  { id: 129, name: "ProductShoot Pro", category: "photography", desc: "Product & listing photography", price: "799", discount: "12% off", rating: 4.7, contact: { personName: "Divya Jadhav", phone: "9889001322" } },
  { id: 130, name: "TechFix Computers", category: "it", desc: "Laptop & PC repair at home", price: "349", discount: "10% off", rating: 4.8, contact: { personName: "Nikhil Mane", phone: "9890101323" } },
  { id: 131, name: "DataSafe Recovery", category: "it", desc: "Data recovery & backup solutions", price: "499", discount: "8% off", rating: 4.7, contact: { personName: "Siddharth Shinde", phone: "9901201324" } },
  { id: 132, name: "PrinterDoc Services", category: "it", desc: "Printer setup, repair & cartridge", price: "299", discount: "12% off", rating: 4.5, contact: { personName: "Tejas Deshpande", phone: "9912301325" } },
  { id: 133, name: "SmartHome Setup", category: "it", desc: "Alexa, Google Home & smart device setup", price: "399", discount: "10% off", rating: 4.8, contact: { personName: "Omkar Wagh", phone: "9923401326" } },
  { id: 134, name: "GamingRig Pro", category: "it", desc: "Gaming PC setup, upgrades & repair", price: "599", discount: "8% off", rating: 4.9, contact: { personName: "Yash Kale", phone: "9934501327" } },
  { id: 135, name: "NetworkNinja", category: "it", desc: "LAN, NAS & home network setup", price: "449", discount: "10% off", rating: 4.7, contact: { personName: "Pratik Thakur", phone: "9945601328" } },
  { id: 136, name: "VirusKill Services", category: "it", desc: "Virus removal & system cleanup", price: "249", discount: "15% off", rating: 4.6, contact: { personName: "Harsh Chavan", phone: "9956701329" } },
  { id: 137, name: "SwiftCourier Local", category: "courier", desc: "Same-day local parcel delivery", price: "79", discount: "Society rate", rating: 4.7, contact: { personName: "Sachin Kamble", phone: "9967801330" } },
  { id: 138, name: "DocDrop Services", category: "courier", desc: "Document & legal paper delivery", price: "99", discount: "10% off", rating: 4.6, contact: { personName: "Vishal Lokhande", phone: "9978901331" } },
  { id: 139, name: "GroceryRun Express", category: "courier", desc: "Grocery & essentials pickup & delivery", price: "49", discount: "15% off", rating: 4.5, contact: { personName: "Rahul Thorat", phone: "9989001332" } },
  { id: 140, name: "MedDelivery Plus", category: "courier", desc: "Medicine & pharmacy delivery", price: "59", discount: "Society rate", rating: 4.8, contact: { personName: "Amit Gaikwad", phone: "9990101333" } },
  { id: 141, name: "MelodyMakers Music", category: "music", desc: "Guitar, keyboard & vocal lessons", price: "499", discount: "10% off", rating: 4.8, contact: { personName: "Priya Waghmare", phone: "9901201334" } },
  { id: 142, name: "BeatBox DJ Classes", category: "music", desc: "DJ & music production classes", price: "699", discount: "8% off", rating: 4.7, contact: { personName: "Neha Dhole", phone: "9812301335" } },
  { id: 143, name: "DanceGroove Studio", category: "music", desc: "Bollywood & western dance classes", price: "399", discount: "12% off", rating: 4.9, contact: { personName: "Pooja Surve", phone: "9823401336" } },
  { id: 144, name: "TablaSitar Academy", category: "music", desc: "Classical Indian music lessons", price: "549", discount: "10% off", rating: 4.8, contact: { personName: "Anjali Bhoir", phone: "9834501337" } },
  { id: 145, name: "BrightMinds Tutors", category: "tutoring", desc: "Home tuition for grades 1-12", price: "399", discount: "10% off", rating: 4.8, contact: { personName: "Sunita Agre", phone: "9845601338" } },
  { id: 146, name: "CodeKids Classes", category: "tutoring", desc: "Coding & robotics for children", price: "499", discount: "12% off", rating: 4.9, contact: { personName: "Vikram Tandel", phone: "9856701339" } },
  { id: 147, name: "SpokenEnglish Pro", category: "tutoring", desc: "Spoken English & communication skills", price: "349", discount: "10% off", rating: 4.7, contact: { personName: "Kavita Pagare", phone: "9867801340" } },
  { id: 148, name: "MathWiz Academy", category: "tutoring", desc: "Maths & science coaching", price: "449", discount: "8% off", rating: 4.6, contact: { personName: "Meena Kokate", phone: "9878901341" } },
  { id: 149, name: "ArtCraft Classes", category: "tutoring", desc: "Drawing, painting & craft for kids", price: "299", discount: "15% off", rating: 4.7, contact: { personName: "Arjun Mhatre", phone: "9889001342" } },
  { id: 150, name: "ShineCar Doorstep", category: "carwash", desc: "Doorstep car wash & vacuum", price: "199", discount: "10% off", rating: 4.7, contact: { personName: "Rohan Patkar", phone: "9890101343" } },
  { id: 151, name: "DetailKing Pro", category: "carwash", desc: "Full car detailing & ceramic coat", price: "999", discount: "8% off", rating: 4.9, contact: { personName: "Sneha Sawant", phone: "9901201344" } },
  { id: 152, name: "BikeWash Express", category: "carwash", desc: "Two-wheeler wash & polish", price: "99", discount: "15% off", rating: 4.6, contact: { personName: "Akash Pawar", phone: "9912301345" } },
  { id: 153, name: "AutoSpa Services", category: "carwash", desc: "Interior deep clean & odour removal", price: "599", discount: "10% off", rating: 4.8, contact: { personName: "Divya Salvi", phone: "9923401346" } },
  { id: 154, name: "PoolCare Pro", category: "pool", desc: "Swimming pool cleaning & maintenance", price: "799", discount: "10% off", rating: 4.8, contact: { personName: "Nikhil Gawde", phone: "9934501347" } },
  { id: 155, name: "TankScrub Services", category: "pool", desc: "Water tank cleaning & disinfection", price: "499", discount: "12% off", rating: 4.7, contact: { personName: "Siddharth More", phone: "9945601348" } },
  { id: 156, name: "AquaBalance Pool", category: "pool", desc: "Pool chemical balancing & testing", price: "599", discount: "8% off", rating: 4.6, contact: { personName: "Tejas Bhosale", phone: "9956701349" } },
  { id: 157, name: "SumpClean Experts", category: "pool", desc: "Sump & underground tank cleaning", price: "699", discount: "10% off", rating: 4.7, contact: { personName: "Omkar Jadhav", phone: "9967801350" } },
];

// Booking amounts per category
export const BOOKING_AMOUNTS: Record<string, number> = {
  plumbing: 150, electrical: 199, carpentry: 249, furniture: 299,
  construction: 399, painting: 249, cleaning: 299, pest: 349,
  appliance: 199, ac: 299, internet: 149, security: 499,
  gardening: 149, movers: 499, vehicle: 249, laundry: 99,
  water: 149, interior: 499, emergency: 299, maintenance: 149,
  solar: 299, gas: 149, flooring: 349, pet: 149,
  childcare: 249, food: 99, beauty: 149, fitness: 199,
  photography: 499, it: 199, courier: 49, music: 199,
  tutoring: 199, carwash: 99, pool: 299,
};

// Category-based default cost ranges
export const CATEGORY_COST_DEFAULTS: Record<string, string> = {
  plumbing: "Rs. 500 - Rs. 1,500",
  electrical: "Rs. 400 - Rs. 1,200",
  carpentry: "Rs. 800 - Rs. 2,500",
  furniture: "Rs. 500 - Rs. 3,000",
  construction: "Rs. 5,000 - Rs. 50,000",
  painting: "Rs. 3,000 - Rs. 15,000",
  cleaning: "Rs. 500 - Rs. 2,000",
  pest: "Rs. 1,500 - Rs. 5,000",
  appliance: "Rs. 300 - Rs. 1,500",
  ac: "Rs. 500 - Rs. 2,500",
  internet: "Rs. 300 - Rs. 800",
  security: "Rs. 3,000 - Rs. 15,000",
  gardening: "Rs. 500 - Rs. 2,000",
  movers: "Rs. 3,000 - Rs. 15,000",
  vehicle: "Rs. 500 - Rs. 3,000",
  laundry: "Rs. 150 - Rs. 600",
  water: "Rs. 300 - Rs. 1,000",
  interior: "Rs. 10,000 - Rs. 1,00,000",
  emergency: "Rs. 500 - Rs. 5,000",
  maintenance: "Rs. 300 - Rs. 1,500",
  solar: "Rs. 500 - Rs. 10,000",
  gas: "Rs. 300 - Rs. 2,000",
  flooring: "Rs. 1,000 - Rs. 20,000",
  pet: "Rs. 200 - Rs. 1,000",
  childcare: "Rs. 500 - Rs. 3,000",
  food: "Rs. 100 - Rs. 5,000",
  beauty: "Rs. 200 - Rs. 2,000",
  fitness: "Rs. 300 - Rs. 1,500",
  photography: "Rs. 500 - Rs. 10,000",
  it: "Rs. 300 - Rs. 3,000",
  courier: "Rs. 50 - Rs. 500",
  music: "Rs. 500 - Rs. 2,000",
  tutoring: "Rs. 300 - Rs. 1,500",
  carwash: "Rs. 200 - Rs. 1,500",
  pool: "Rs. 500 - Rs. 5,000",
};
