-- ============================================================
-- Community Posts seed — Greenwood Heights Co-op Housing Society
-- Realistic posts from actual members, before 17 Mar 2026
-- ============================================================

DELETE FROM post_likes;
DELETE FROM post_comments;
DELETE FROM community_posts;

INSERT INTO community_posts (user_id, content, created_at)
SELECT p.id, v.content, v.created_at::timestamptz
FROM (VALUES
  ('moksh.sonar@gmail.com',     'Reminder: Society AGM minutes from June 2025 are now available in the Document Vault. Please review the resolutions passed, especially regarding the terrace waterproofing project. — Secretary',                                                          '2026-01-05 10:00:00'),
  ('rajesh.patil@gmail.com',    'Good morning everyone! Just wanted to say the new garden area near D Wing looks absolutely beautiful. Great work by the maintenance team. 🌿',                                                                                                         '2026-01-09 08:30:00'),
  ('purva.chavan@gmail.com',    'Maintenance charges for January 2026 are due by 10th January. Please ensure timely payment to avoid late fees. UPI and online payment options are available. — Treasurer',                                                                            '2026-01-07 09:00:00'),
  ('sunita.kulkarni@gmail.com', 'Does anyone know a good plumber in Kharghar? My kitchen tap has been dripping for 2 days. Please share contact if you have one. Thanks!',                                                                                                           '2026-01-11 11:15:00'),
  ('yash.bandawane@gmail.com',  'Reminder from the committee: Please do not park vehicles in front of the fire exit near B Wing. It is a safety violation and action will be taken for repeat offenders.',                                                                            '2026-01-13 09:30:00'),
  ('ganesh.shinde@gmail.com',   'Happy Makar Sankranti to all residents! 🪁 Our rooftop kite flying event was a huge success. Thank you to everyone who participated. See you all next year!',                                                                                        '2026-01-14 18:00:00'),
  ('meera.jadhav@gmail.com',    'Looking for a reliable babysitter for weekday evenings. My daughter is 4 years old. If anyone can recommend someone trustworthy in the society please DM me.',                                                                                       '2026-01-16 14:00:00'),
  ('aryan.chauhan@gmail.com',   'The CCTV upgrade for all 4 wings has been completed today. We now have 24 cameras covering all entry/exit points, parking areas and common corridors. Stay safe everyone! 📷',                                                                       '2026-01-20 17:00:00'),
  ('suresh.deshmukh@gmail.com', 'Selling: Godrej refrigerator 310L, 5 years old, excellent condition. Reason: upgrading. Price: ₹12,000 negotiable. Contact me at A-401 or call 9823401005.',                                                                                        '2026-01-23 10:00:00'),
  ('kavita.gaikwad@gmail.com',  'The ladies kitty group is meeting this Sunday at 4 PM in the clubhouse. All ladies of the society are welcome! Light snacks will be served. Please confirm attendance.',                                                                              '2026-01-25 12:00:00'),
  ('nilesh.bhosale@gmail.com',  'Just a heads up — there was a suspicious person loitering near the A Wing parking last night around 11 PM. I have informed the security guard. Please be alert and report anything unusual.',                                                         '2026-01-28 07:45:00'),
  ('tanmay.kolekar@gmail.com',  'Cricket match this Sunday! Society vs Sector 8 Housing Society. 7 AM at the ground near the school. We need 4 more players. Interested residents please comment below. 🏏',                                                                          '2026-01-30 20:00:00'),
  ('priya.pawar@gmail.com',     'Congratulations to little Aarav from B-402 for winning the district-level drawing competition! 🎨 So proud of our young talent. The society celebrates with you!',                                                                                   '2026-02-02 11:00:00'),
  ('purva.chavan@gmail.com',    'February maintenance dues reminder. ₹2,500 per flat due by 10th Feb. 23 flats still have January dues pending — please clear at the earliest to avoid penalty. — Treasurer',                                                                         '2026-02-05 09:00:00'),
  ('amol.mane@gmail.com',       'The society gym has been restocked with new equipment! New treadmill, dumbbells set and yoga mats are now available. Gym timings: 5 AM – 10 PM. Please maintain cleanliness.',                                                                       '2026-02-08 08:00:00'),
  ('sneha.waghmare@gmail.com',  'Holi celebration planning meeting this Saturday at 6 PM in the clubhouse. We need volunteers for decoration, colours and food arrangements. Please join and contribute ideas! 🎨',                                                                    '2026-02-10 15:30:00'),
  ('rohini.jadhav@gmail.com',   'Lost: Black umbrella with red handle, left in the A Wing lift yesterday evening. If found please contact flat B-301. Thank you.',                                                                                                                   '2026-02-12 09:00:00'),
  ('moksh.sonar@gmail.com',     'Important: The terrace waterproofing work for A & B Wing will begin on 15th February. Residents of these wings please ensure the terrace access door is unlocked. Work will take approx 5 days. — Secretary',                                        '2026-02-13 10:00:00'),
  ('vikas.deshpande@gmail.com', 'Holi was amazing this year! 🎉 Thank you to the organizing committee and all volunteers. The bhang thandai was a hit. Looking forward to more such events!',                                                                                         '2026-02-17 19:00:00'),
  ('rekha.salunkhe@gmail.com',  'Yoga classes starting from 1st March every morning 6:30 AM to 7:30 AM in the garden area. Open to all residents. No charges. Conducted by Mrs. Sharma from C-802. Join us! 🧘',                                                                     '2026-02-20 08:00:00'),
  ('pramod.kale@gmail.com',     'Anyone interested in forming a society WhatsApp group for buying vegetables and groceries in bulk? We can get better rates if we order together. Reply if interested.',                                                                               '2026-02-22 11:00:00'),
  ('aryan.chauhan@gmail.com',   'Reminder: Parking rules are strictly enforced from this month. Vehicles without society stickers will be towed at owner''s expense. Please collect your sticker from the security cabin.',                                                            '2026-02-24 09:30:00'),
  ('ashwini.nimkar@gmail.com',  'The reading club meets every 2nd and 4th Saturday at 5 PM in the clubhouse library. This month we are discussing "The Palace of Illusions". New members welcome! 📚',                                                                                '2026-02-26 14:00:00'),
  ('purva.chavan@gmail.com',    'March maintenance dues are now open. Please pay by 10th March. Residents with 3+ months pending dues will be listed on the notice board as per society bye-laws. — Treasurer',                                                                       '2026-03-01 09:00:00'),
  ('deepak.thakare@gmail.com',  'The water pressure issue on upper floors has been escalated to the committee. A plumber has been called for inspection on 3rd March. Residents on floors 10-14 please bear with us.',                                                                '2026-03-02 10:00:00'),
  ('pooja.kamble@gmail.com',    'Congratulations to our society cricket team for winning the inter-society tournament! 🏆 Special thanks to Tanmay bhai for organizing everything. Champions! 🏏',                                                                                    '2026-03-04 20:00:00'),
  ('sachin.mohite@gmail.com',   'Selling: Honda Activa 5G 2021 model, 18,000 km driven, single owner, all documents clear. Price ₹58,000 final. Interested buyers contact A-1001.',                                                                                                  '2026-03-06 11:00:00'),
  ('yash.bandawane@gmail.com',  'Fire drill scheduled for Sunday 8th March at 10 AM. All residents are requested to participate. The drill will cover evacuation procedures for all 4 wings. Takes approx 45 minutes.',                                                               '2026-03-07 09:00:00'),
  ('varsha.lokhande@gmail.com', 'The fire drill went very smoothly! All 4 wings evacuated in under 8 minutes. Great cooperation from all residents. Special thanks to the security team. Stay safe! 🔥',                                                                              '2026-03-08 12:00:00'),
  ('rahul.gavhane@gmail.com',   'Anyone know if the Kharghar node CIDCO office is open on Saturdays? Need to get some documents attested. Please reply if you have recent experience.',                                                                                               '2026-03-10 10:30:00'),
  ('moksh.sonar@gmail.com',     'Society elections for the new managing committee will be held on 30th March 2026. Nomination forms available at the secretary''s office (A-301) from 15th March. All eligible members please participate. — Secretary',                              '2026-03-12 10:00:00'),
  ('smita.bansode@gmail.com',   'Gudi Padwa celebration on 30th March! Planning committee meeting this Friday at 7 PM in the clubhouse. We need volunteers for rangoli, decoration and food. Please join! 🪔',                                                                        '2026-03-13 15:00:00'),
  ('mahesh.ingale@gmail.com',   'The water pressure on 12th floor is still very low. It has been 2 weeks now. Requesting the committee to treat this as urgent. We are managing with stored water but it is not sustainable.',                                                         '2026-03-15 08:30:00'),
  ('purva.chavan@gmail.com',    'Final reminder: March maintenance dues deadline is tomorrow 10th March. 31 flats still pending. Please pay today to avoid late fee of ₹200. — Treasurer',                                                                                            '2026-03-16 09:00:00'),
  ('tanmay.kolekar@gmail.com',  'Good news! The broken tiles around the swimming pool will be repaired this week. Pool will be closed from 18th to 22nd March for repair work. Sorry for the inconvenience. — Committee', '2026-03-17 08:00:00')
) AS v(email, content, created_at)
JOIN profiles p ON p.email = v.email;
