-- ISSUES SEED PART 5

INSERT INTO issues (title, description, category, priority, status, created_at) VALUES
('Waterproofing needed — terrace B Wing', 'Terrace of B-Wing showing cracks. Water seeping into top floor flats.', 'Maintenance', 'high', 'open', NOW() - INTERVAL '5 days'),
('Broken door closer — main entrance', 'Main entrance door closer broken. Door banging loudly.', 'Maintenance', 'medium', 'open', NOW() - INTERVAL '11 days'),
('Pest control needed — D Wing', 'Cockroach infestation reported in multiple D-Wing flats. Society-level treatment needed.', 'Housekeeping', 'high', 'open', NOW() - INTERVAL '3 days'),
('Unauthorized banner on society wall', 'Political banner pasted on society boundary wall without permission.', 'Security', 'low', 'open', NOW() - INTERVAL '13 days'),
('Table tennis table damaged', 'Table tennis table surface cracked. Cannot be used.', 'Amenities', 'low', 'open', NOW() - INTERVAL '16 days'),
('Party noise from terrace — weekend', 'Loud party on terrace every Saturday night till 2 AM.', 'Noise', 'high', 'open', NOW() - INTERVAL '4 days'),
('Visitor parking time limit violation', 'Same vehicle in visitor parking for 3 days. No action taken.', 'Parking', 'medium', 'open', NOW() - INTERVAL '8 days'),
('Tap leaking in common bathroom', 'Tap in ground floor common bathroom leaking continuously. Water wastage.', 'Plumbing', 'medium', 'open', NOW() - INTERVAL '6 days'),
('Lift indicator light broken — B Wing', 'Floor indicator display inside Lift B not working.', 'Maintenance', 'low', 'open', NOW() - INTERVAL '14 days'),
('Garbage collection timing issue', 'Garbage collected at 5 AM. Residents unable to put out bins in time.', 'Housekeeping', 'medium', 'open', NOW() - INTERVAL '7 days'),
('Staircase handrail loose — A Wing floor 3', 'Handrail on A-Wing 3rd floor staircase is loose. Elderly residents at risk.', 'Maintenance', 'high', 'open', NOW() - INTERVAL '4 days'),
('Electrical short circuit — D-Wing meter room', 'Short circuit in D-Wing meter room. Burning smell reported.', 'Electrical', 'critical', 'in_progress', NOW() - INTERVAL '12 hours'),
('Waterlogging in parking after rain', 'Parking area floods after every rain. Vehicles getting damaged.', 'Maintenance', 'high', 'open', NOW() - INTERVAL '3 days'),
('Society notice board damaged', 'Notice board near main gate is broken. Notices falling off.', 'Maintenance', 'low', 'open', NOW() - INTERVAL '18 days'),
('Gym locker broken', 'Locker number 4 in gym changing room is broken. Cannot be locked.', 'Amenities', 'low', 'open', NOW() - INTERVAL '15 days'),
('Noise from water pump at night', 'Water pump running loudly between 11 PM and 1 AM. Disturbing residents.', 'Noise', 'medium', 'open', NOW() - INTERVAL '9 days'),
('Bike stand full — no space', 'Two-wheeler parking stand completely full. New residents have no space.', 'Parking', 'medium', 'open', NOW() - INTERVAL '10 days'),
('Overhead tank cleaning overdue', 'Overhead tank not cleaned in 6 months. Water quality concern.', 'Plumbing', 'high', 'open', NOW() - INTERVAL '2 days'),
('Corridor light timer wrong', 'Corridor lights in C-Wing turning off at 9 PM. Too early.', 'Electrical', 'low', 'open', NOW() - INTERVAL '12 days'),
('Lift D weight sensor issue', 'Lift D showing overload with only 4 people. Sensor needs calibration.', 'Maintenance', 'medium', 'in_progress', NOW() - INTERVAL '5 days'),
('Broken bench — kids play area', 'Bench near kids play area broken. Parents have no place to sit.', 'Amenities', 'low', 'open', NOW() - INTERVAL '17 days'),
('Loud TV from A-601 late night', 'Resident in A-601 watches TV at very high volume after 11 PM.', 'Noise', 'low', 'open', NOW() - INTERVAL '11 days'),
('Parking slot paint faded — B Wing', 'Parking slot numbers in B-Wing area faded. Causing disputes.', 'Parking', 'low', 'open', NOW() - INTERVAL '20 days'),
('Pipe corrosion — A-Wing riser', 'Main water riser pipe in A-Wing showing corrosion. Risk of burst.', 'Plumbing', 'high', 'open', NOW() - INTERVAL '4 days'),
('Power socket sparking — B-Wing lobby', 'Power socket in B-Wing lobby sparking when plugged. Fire risk.', 'Electrical', 'critical', 'open', NOW() - INTERVAL '1 day'),
('Garden lights not working', 'Garden pathway lights not working. Dark and unsafe at night.', 'Electrical', 'medium', 'open', NOW() - INTERVAL '8 days'),
('Clubhouse chairs damaged', 'Several chairs in clubhouse have broken legs. Replacement needed.', 'Amenities', 'medium', 'open', NOW() - INTERVAL '9 days'),
('Renovation dust affecting asthma patients', 'Renovation in C-Wing creating dust. Resident with asthma severely affected.', 'Noise', 'high', 'open', NOW() - INTERVAL '5 days'),
('Unauthorized parking — fire exit', 'Vehicle parked blocking fire exit near D-Wing. Emergency access blocked.', 'Parking', 'critical', 'open', NOW() - INTERVAL '2 days'),
('Sump pump not working', 'Underground sump pump not working. Water not reaching overhead tanks.', 'Plumbing', 'critical', 'in_progress', NOW() - INTERVAL '6 hours'),
('Transformer humming loudly', 'Society transformer making loud humming noise. Residents concerned.', 'Electrical', 'high', 'open', NOW() - INTERVAL '6 days'),
('Jogging track surface cracked', 'Jogging track surface has multiple cracks. Ankle injury risk.', 'Maintenance', 'medium', 'open', NOW() - INTERVAL '10 days'),
('Pest control chemicals smell', 'Strong chemical smell after pest control in B-Wing. Residents feeling unwell.', 'Housekeeping', 'medium', 'open', NOW() - INTERVAL '7 days'),
('Guard not checking visitor ID', 'Security guard allowing visitors without ID verification.', 'Security', 'high', 'open', NOW() - INTERVAL '3 days'),
('Pool changing room lock broken', 'Changing room lock near pool broken. No privacy.', 'Amenities', 'medium', 'open', NOW() - INTERVAL '12 days'),
('Drilling noise from D-401', 'Drilling work in D-401 from 8 AM to 6 PM daily for 2 weeks.', 'Noise', 'medium', 'open', NOW() - INTERVAL '8 days'),
('Parking area CCTV not recording', 'Parking area CCTV camera recording light is off. Not recording.', 'Security', 'high', 'open', NOW() - INTERVAL '4 days'),
('Drain cover missing — A Wing', 'Drain cover near A-Wing entrance missing. Fall hazard.', 'Maintenance', 'high', 'open', NOW() - INTERVAL '3 days'),
('Water meter room flooding', 'Water meter room flooding during rain. Meters getting wet.', 'Plumbing', 'high', 'open', NOW() - INTERVAL '5 days'),
('Lift A rope inspection overdue', 'Lift A rope inspection certificate expired 2 months ago.', 'Maintenance', 'critical', 'open', NOW() - INTERVAL '2 days'),
('Electrical panel door open', 'Main electrical panel door in D-Wing basement left open. Safety hazard.', 'Electrical', 'high', 'open', NOW() - INTERVAL '4 days'),
('Gym water dispenser empty', 'Water dispenser in gym empty for 3 days. No drinking water available.', 'Amenities', 'medium', 'open', NOW() - INTERVAL '6 days'),
('Loud argument in common area', 'Residents having loud arguments in common area near B-Wing entrance.', 'Noise', 'low', 'open', NOW() - INTERVAL '13 days'),
('Parking slot dispute — A-07 and A-08', 'Two residents claiming same parking slot. Needs admin resolution.', 'Parking', 'medium', 'open', NOW() - INTERVAL '9 days'),
('Bathroom exhaust fan broken — C-Wing', 'Common bathroom exhaust fan on C-Wing ground floor not working.', 'Maintenance', 'low', 'open', NOW() - INTERVAL '16 days'),
('Water tank bird netting torn', 'Bird netting on overhead tank torn. Birds entering tank area.', 'Maintenance', 'medium', 'open', NOW() - INTERVAL '11 days'),
('Lift B floor gap too wide', 'Gap between Lift B and floor is too wide. Elderly residents struggling.', 'Maintenance', 'high', 'open', NOW() - INTERVAL '4 days'),
('Garbage bin lids missing', 'Lids of garbage bins near C-Wing missing. Smell and flies.', 'Housekeeping', 'medium', 'open', NOW() - INTERVAL '7 days'),
('Visitor log not maintained', 'Security guard not maintaining visitor log book properly.', 'Security', 'medium', 'open', NOW() - INTERVAL '8 days');
