f = open('society-hub/app/dashboard/documents/page.tsx', 'rb')
data = f.read()
f.close()
data = data.replace(b'\xe2\x80\x93', b'-')
data = data.replace(b'\xe2\x80\xa2', b'*')
data = data.replace(b'\xe2\x82\xb9', b'Rs.')
data = data.replace(b'\xe2\x9c\x93', b'OK')
data = data.replace(b'\xe2\x86\x92', b'->')
f = open('society-hub/app/dashboard/documents/page.tsx', 'wb')
f.write(data)
f.close()
print('Done')
